MANIFEST: "manifest.rest.localrun.tsv"
WORK_DIR: "/tmp/global2/ssushko/TE_evolution/1001Gp_TE_ANNOT/panTEome_v3_1001Gp/annotation"
resources:
    threads: 20
params:
    min_fl_copy: 3
scripts:
  cleanup_nested: "scripts_for_snakepipe/cleanup_nested.pl"
  find_flTE: "scripts_for_snakepipe/find_flTE.pl"
extra_datasets:
  curatedlib: "/tmp/global2/ssushko/TE_evolution/1001Gp_TE_ANNOT/curatedlib/colcc-pantera_v2.1.fa"
  trash_annot_dir: "/tmp/global2/ssushko/TE_evolution/EDTA_reannot/panTEome_v2/repeat_annot/TRASH_45S"

